version: 2
jobs:
  build:
    working_directory: ~/andrew.fm
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Installing...
          command: npm install
      - run:
          name: Building...
          command: npm run build
